tasks:
  - init: docker-compose pull appwrite --include-deps
    command: |
      docker-compose up

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
  - port: 443
    onOpen: ignore
    visibility: public
  - port: 3001
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker
