tasks:
  - init: docker-compose pull --include-deps appwrite traefik
    command: |
      DOMAIN=$(echo $GITPOD_WORKSPACE_URL | sed 's/https:\/\/appwrite/8080-appwrite/g')
      sed -i "s/_APP_DOMAIN=localhost/_APP_DOMAIN=$DOMAIN/g" .env
      sed -i "s/_APP_DOMAIN_FUNCTIONS=localhost/_APP_DOMAIN_FUNCTIONS=$DOMAIN/g" .env
      sed -i "s/_APP_DOMAIN_TARGET=localhost/_APP_DOMAIN_TARGET=$DOMAIN/g" .env
      docker compose up

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
  - port: 443
    onOpen: ignore
    visibility: public
  - port: 3001
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker
